services:
  web:
    image: nginx:latest
    container_name: web_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/usr/share/nginx/html
      - ./docker_config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker_config/certs:/etc/nginx/certs
    networks:
      - webnet
  
  logserver:
    build: 
      dockerfile: ./docker_config/logserver/Dockerfile
      context: ./docker_config/logserver
    ports:
      - "5000:5000"
    volumes:
      - ./docker_config/logserver/app.py:/app/app.py
      - ./docker_config/logserver/app.log:/app/app.log
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
