services:
  web:
    image: nginx:latest
    container_name: web_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/usr/share/nginx/html
      - ./docker_config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker_config/certs:/etc/nginx/certs
  
  logger:
    image: python:3.11-slim
    volumes:
      - ./docker_config/logger:/app
    command: >
      sh -c "pip install flask && python -u /app/logger.py"
    ports:
      - "5000:5000"
    working_dir: /app
